In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
heart = pd.read_csv('heart.csv')

In [3]:
heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
heart.shape

(303, 14)

In [5]:
heart.dtypes  #print the datatypes of values in each column

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [6]:
heart.isnull().sum()  #print the total number of missing values column-wise

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
heart.isnull().sum(axis = 1)  #print the total number of missing values row-wise

0      0
1      0
2      0
3      0
4      0
      ..
298    0
299    0
300    0
301    0
302    0
Length: 303, dtype: int64

In [8]:
heart.duplicated().sum()  #print the total number of rows which are duplicates

np.int64(1)

In [9]:
heart[heart.duplicated()]  #print all the duplicate rows

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1

In [10]:
heart[heart.duplicated(subset = ['trestbps', 'chol'])]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
113,43,1,0,110,211,0,1,161,0,0.0,2,0,3,1
140,51,0,2,120,295,0,0,157,0,0.6,2,0,2,1
155,58,0,0,130,197,0,1,131,0,0.6,1,0,2,1
160,56,1,1,120,240,0,1,169,0,0.0,0,0,2,1
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1
170,56,1,2,130,256,1,0,142,1,0.6,1,1,1,0
178,43,1,0,120,177,0,0,120,1,2.5,1,0,3,0
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3,0
186,60,1,0,130,253,0,1,144,1,1.4,2,1,3,0
191,58,1,0,128,216,0,0,131,1,2.2,1,3,3,0
208,49,1,2,120,188,0,1,139,0,2.0,1,3,3,0
217,63,1,0,130,330,1,0,132,1,1.8,2,3,3,0
219,48,1,0,130,256,1,0,150,1,0.0,2,2,3,0
224,54,1,0,110,239,0,1,126,1,2.8,1,1,3,0
261,52,1,0,112,230,0,1,160,0,0.0,2,1,2,0
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3,0

In [11]:
heart.drop_duplicates(inplace = True)

In [ ]:
X = heart.drop(columns = 'target')#store all the input columns
y = heart['target']   #store the output column

In [ ]:
#split the data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 100)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
log_reg.coef_  #m1 to m13

array([[ 0.02651805, -0.76115681,  0.78058821, -0.2162428 , -0.45756905,
        -0.11290994,  0.0609823 ,  0.44218324, -0.33736004, -0.5613874 ,
         0.37441386, -0.68913694, -0.62006129]])

In [ ]:
log_reg.intercept_  #c value

array([0.30759926])

In [ ]:
y_pred = log_reg.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test, y_pred)

0.819672131147541

In [ ]:
from sklearn.metrics import precision_score, recall_score

In [ ]:
precision_score(y_test, y_pred)

0.7575757575757576

In [ ]:
recall_score(y_test, y_pred)

0.8928571428571429